package com.luxsoft.cfdi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.6
 * 2014-10-13T09:32:14.180-05:00
 * Generated source version: 2.6.6
 * 
 */
@WebServiceClient(name = "ConsultaCFDIService", 
                  wsdlLocation = "https://consultaqr.facturaelectronica.sat.gob.mx/ConsultaCFDIService.svc?singleWsdl",
                  targetNamespace = "http://tempuri.org/") 
public class ConsultaCFDIService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "ConsultaCFDIService");
    public final static QName BasicHttpBindingIConsultaCFDIService = new QName("http://tempuri.org/", "BasicHttpBinding_IConsultaCFDIService");
    static {
        URL url = null;
        try {
            url = new URL("https://consultaqr.facturaelectronica.sat.gob.mx/ConsultaCFDIService.svc?singleWsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ConsultaCFDIService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://consultaqr.facturaelectronica.sat.gob.mx/ConsultaCFDIService.svc?singleWsdl");
        }
        WSDL_LOCATION = url;
    }

    public ConsultaCFDIService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConsultaCFDIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaCFDIService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConsultaCFDIService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConsultaCFDIService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConsultaCFDIService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IConsultaCFDIService
     */
    @WebEndpoint(name = "BasicHttpBinding_IConsultaCFDIService")
    public IConsultaCFDIService getBasicHttpBindingIConsultaCFDIService() {
        return super.getPort(BasicHttpBindingIConsultaCFDIService, IConsultaCFDIService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IConsultaCFDIService
     */
    @WebEndpoint(name = "BasicHttpBinding_IConsultaCFDIService")
    public IConsultaCFDIService getBasicHttpBindingIConsultaCFDIService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIConsultaCFDIService, IConsultaCFDIService.class, features);
    }

}
