/*
 * Generated by JasperReports - 22/02/17 03:35 PM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import net.sf.jasperreports.engine.*;
import java.util.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class NominaDigitalCFDI_Res_1487799309773_115600 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_SALARIO_DIARIO_INTEGRADO = null;
    private JRFillParameter parameter_TIPO_NOMINA = null;
    private JRFillParameter parameter_SUCURSAL = null;
    private JRFillParameter parameter_NUM_CERTIFICADO = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_BANCO = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_TOTAL = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_NUMERO_EMPLEADO = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_REGIMEN_TRABAJADOR = null;
    private JRFillParameter parameter_EMISOR_DIRECCION = null;
    private JRFillParameter parameter_QR_CODE = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_TOTAL_1 = null;
    private JRFillParameter parameter_IMPORTE_INCAPACIDAD = null;
    private JRFillParameter parameter_FECHA_INICIAL = null;
    private JRFillParameter parameter_RAMO = null;
    private JRFillParameter parameter_IMPORTE_HORAS_EXTRA = null;
    private JRFillParameter parameter_GRUPO = null;
    private JRFillParameter parameter_METODO_DE_PAGO = null;
    private JRFillParameter parameter_FECHA_INGRESO_LABORAL = null;
    private JRFillParameter parameter_COMPANY = null;
    private JRFillParameter parameter_ANTIGUEDAD = null;
    private JRFillParameter parameter_NOMBRE = null;
    private JRFillParameter parameter_TIPO_INCAPACIDAD = null;
    private JRFillParameter parameter_FECHA = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_SALARIO_DIARIO_BASE = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_DEPARTAMENTO = null;
    private JRFillParameter parameter_RFC = null;
    private JRFillParameter parameter_TIPO_HORAS = null;
    private JRFillParameter parameter_EMISOR_NOMBRE = null;
    private JRFillParameter parameter_FECHA_TIMBRADO = null;
    private JRFillParameter parameter_CLABE = null;
    private JRFillParameter parameter_TIPO_CFDI = null;
    private JRFillParameter parameter_TIPO_CONTRATO = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_PERIOCIDAD_PAGO = null;
    private JRFillParameter parameter_SELLO_DIGITAL_SAT = null;
    private JRFillParameter parameter_DIAS_INCAPACIDAD = null;
    private JRFillParameter parameter_TIPO = null;
    private JRFillParameter parameter_REPORT_FILE_RESOLVER = null;
    private JRFillParameter parameter_CURP = null;
    private JRFillParameter parameter_REGISTRO_PATRONAL = null;
    private JRFillParameter parameter_CADENA_ORIGINAL_SAT = null;
    private JRFillParameter parameter_SUB_EMPLEO_APLIC = null;
    private JRFillParameter parameter_RIESGO_PUESTO = null;
    private JRFillParameter parameter_IMP_CON_LETRA = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_SELLO_DIGITAL = null;
    private JRFillParameter parameter_EMISOR_RFC = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_NFISCAL = null;
    private JRFillParameter parameter_HORAS_EXTRA = null;
    private JRFillParameter parameter_EMPRESA_LOGO = null;
    private JRFillParameter parameter_TIPO_JORNADA = null;
    private JRFillParameter parameter_FALTAS = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_DIAS_HORAS_EXTRA = null;
    private JRFillParameter parameter_CERTIFICADO_SAT = null;
    private JRFillParameter parameter_DESTINATARIO = null;
    private JRFillParameter parameter_NUMERO_IMSS = null;
    private JRFillParameter parameter_COMENTARIO_NOM = null;
    private JRFillParameter parameter_PUESTO = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_DIAS_TRABAJADOS = null;
    private JRFillParameter parameter_FECHA_FINAL = null;
    private JRFillParameter parameter_FOLIO_FISCAL = null;
    private JRFillField field_CONCEPTO = null;
    private JRFillField field_IMPORTE_GRAVADO = null;
    private JRFillField field_CLAVE = null;
    private JRFillField field_IMPORTE_EXENTO = null;
    private JRFillField field_DESCRIPCION = null;
    private JRFillField field_GRUPO = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_GRUPO1_COUNT = null;
    private JRFillVariable variable_TOTAL_GRUPO_EXENTO = null;
    private JRFillVariable variable_TOTAL_GRUPO_GRAVADO = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_SALARIO_DIARIO_INTEGRADO = (JRFillParameter)pm.get("SALARIO_DIARIO_INTEGRADO");
        parameter_TIPO_NOMINA = (JRFillParameter)pm.get("TIPO_NOMINA");
        parameter_SUCURSAL = (JRFillParameter)pm.get("SUCURSAL");
        parameter_NUM_CERTIFICADO = (JRFillParameter)pm.get("NUM_CERTIFICADO");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_BANCO = (JRFillParameter)pm.get("BANCO");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_TOTAL = (JRFillParameter)pm.get("TOTAL");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_NUMERO_EMPLEADO = (JRFillParameter)pm.get("NUMERO_EMPLEADO");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_REGIMEN_TRABAJADOR = (JRFillParameter)pm.get("REGIMEN_TRABAJADOR");
        parameter_EMISOR_DIRECCION = (JRFillParameter)pm.get("EMISOR_DIRECCION");
        parameter_QR_CODE = (JRFillParameter)pm.get("QR_CODE");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_TOTAL_1 = (JRFillParameter)pm.get("TOTAL_1");
        parameter_IMPORTE_INCAPACIDAD = (JRFillParameter)pm.get("IMPORTE_INCAPACIDAD");
        parameter_FECHA_INICIAL = (JRFillParameter)pm.get("FECHA_INICIAL");
        parameter_RAMO = (JRFillParameter)pm.get("RAMO");
        parameter_IMPORTE_HORAS_EXTRA = (JRFillParameter)pm.get("IMPORTE_HORAS_EXTRA");
        parameter_GRUPO = (JRFillParameter)pm.get("GRUPO");
        parameter_METODO_DE_PAGO = (JRFillParameter)pm.get("METODO_DE_PAGO");
        parameter_FECHA_INGRESO_LABORAL = (JRFillParameter)pm.get("FECHA_INGRESO_LABORAL");
        parameter_COMPANY = (JRFillParameter)pm.get("COMPANY");
        parameter_ANTIGUEDAD = (JRFillParameter)pm.get("ANTIGUEDAD");
        parameter_NOMBRE = (JRFillParameter)pm.get("NOMBRE");
        parameter_TIPO_INCAPACIDAD = (JRFillParameter)pm.get("TIPO_INCAPACIDAD");
        parameter_FECHA = (JRFillParameter)pm.get("FECHA");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_SALARIO_DIARIO_BASE = (JRFillParameter)pm.get("SALARIO_DIARIO_BASE");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_DEPARTAMENTO = (JRFillParameter)pm.get("DEPARTAMENTO");
        parameter_RFC = (JRFillParameter)pm.get("RFC");
        parameter_TIPO_HORAS = (JRFillParameter)pm.get("TIPO_HORAS");
        parameter_EMISOR_NOMBRE = (JRFillParameter)pm.get("EMISOR_NOMBRE");
        parameter_FECHA_TIMBRADO = (JRFillParameter)pm.get("FECHA_TIMBRADO");
        parameter_CLABE = (JRFillParameter)pm.get("CLABE");
        parameter_TIPO_CFDI = (JRFillParameter)pm.get("TIPO_CFDI");
        parameter_TIPO_CONTRATO = (JRFillParameter)pm.get("TIPO_CONTRATO");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_PERIOCIDAD_PAGO = (JRFillParameter)pm.get("PERIOCIDAD_PAGO");
        parameter_SELLO_DIGITAL_SAT = (JRFillParameter)pm.get("SELLO_DIGITAL_SAT");
        parameter_DIAS_INCAPACIDAD = (JRFillParameter)pm.get("DIAS_INCAPACIDAD");
        parameter_TIPO = (JRFillParameter)pm.get("TIPO");
        parameter_REPORT_FILE_RESOLVER = (JRFillParameter)pm.get("REPORT_FILE_RESOLVER");
        parameter_CURP = (JRFillParameter)pm.get("CURP");
        parameter_REGISTRO_PATRONAL = (JRFillParameter)pm.get("REGISTRO_PATRONAL");
        parameter_CADENA_ORIGINAL_SAT = (JRFillParameter)pm.get("CADENA_ORIGINAL_SAT");
        parameter_SUB_EMPLEO_APLIC = (JRFillParameter)pm.get("SUB_EMPLEO_APLIC");
        parameter_RIESGO_PUESTO = (JRFillParameter)pm.get("RIESGO_PUESTO");
        parameter_IMP_CON_LETRA = (JRFillParameter)pm.get("IMP_CON_LETRA");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_SELLO_DIGITAL = (JRFillParameter)pm.get("SELLO_DIGITAL");
        parameter_EMISOR_RFC = (JRFillParameter)pm.get("EMISOR_RFC");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_NFISCAL = (JRFillParameter)pm.get("NFISCAL");
        parameter_HORAS_EXTRA = (JRFillParameter)pm.get("HORAS_EXTRA");
        parameter_EMPRESA_LOGO = (JRFillParameter)pm.get("EMPRESA_LOGO");
        parameter_TIPO_JORNADA = (JRFillParameter)pm.get("TIPO_JORNADA");
        parameter_FALTAS = (JRFillParameter)pm.get("FALTAS");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_DIAS_HORAS_EXTRA = (JRFillParameter)pm.get("DIAS_HORAS_EXTRA");
        parameter_CERTIFICADO_SAT = (JRFillParameter)pm.get("CERTIFICADO_SAT");
        parameter_DESTINATARIO = (JRFillParameter)pm.get("DESTINATARIO");
        parameter_NUMERO_IMSS = (JRFillParameter)pm.get("NUMERO_IMSS");
        parameter_COMENTARIO_NOM = (JRFillParameter)pm.get("COMENTARIO_NOM");
        parameter_PUESTO = (JRFillParameter)pm.get("PUESTO");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_DIAS_TRABAJADOS = (JRFillParameter)pm.get("DIAS_TRABAJADOS");
        parameter_FECHA_FINAL = (JRFillParameter)pm.get("FECHA_FINAL");
        parameter_FOLIO_FISCAL = (JRFillParameter)pm.get("FOLIO_FISCAL");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_CONCEPTO = (JRFillField)fm.get("CONCEPTO");
        field_IMPORTE_GRAVADO = (JRFillField)fm.get("IMPORTE_GRAVADO");
        field_CLAVE = (JRFillField)fm.get("CLAVE");
        field_IMPORTE_EXENTO = (JRFillField)fm.get("IMPORTE_EXENTO");
        field_DESCRIPCION = (JRFillField)fm.get("DESCRIPCION");
        field_GRUPO = (JRFillField)fm.get("GRUPO");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_GRUPO1_COUNT = (JRFillVariable)vm.get("GRUPO1_COUNT");
        variable_TOTAL_GRUPO_EXENTO = (JRFillVariable)vm.get("TOTAL_GRUPO_EXENTO");
        variable_TOTAL_GRUPO_GRAVADO = (JRFillVariable)vm.get("TOTAL_GRUPO_GRAVADO");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.String)("FALTA");//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.String)("N/A");//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.String)("N/A");//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.String)("N/A");//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_IMPORTE_EXENTO.getValue()));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_IMPORTE_GRAVADO.getValue()));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_CLAVE.getValue()).substring(0,1));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.lang.String)(((java.math.BigDecimal)variable_TOTAL_GRUPO_EXENTO.getValue()));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.lang.String)(" ".concat(((java.lang.String)field_CONCEPTO.getValue()).equals("P")?" PERCEPCIONES ":" DEDUCCIONES ").concat(" IMPORTE : "));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.lang.String)(new Double(((java.math.BigDecimal)variable_TOTAL_GRUPO_GRAVADO.getValue()).doubleValue()+((java.math.BigDecimal)variable_TOTAL_GRUPO_EXENTO.getValue()).doubleValue()));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.String)("TOTAL: ");//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.lang.String)(((java.math.BigDecimal)variable_TOTAL_GRUPO_GRAVADO.getValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_EMISOR_DIRECCION.getValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.String)(((java.lang.Object)parameter_EMPRESA_LOGO.getValue()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_FOLIO_FISCAL.getValue()));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_FECHA.getValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_NFISCAL.getValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_TIPO_NOMINA.getValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_FECHA_INICIAL.getValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_FECHA_FINAL.getValue()));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_PERIOCIDAD_PAGO.getValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_EMISOR_NOMBRE.getValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_BANCO.getValue()));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_CLABE.getValue()));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_NOMBRE.getValue()));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_NUMERO_IMSS.getValue()));//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_NUMERO_EMPLEADO.getValue()));//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_CURP.getValue()));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_RFC.getValue()));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_TIPO_JORNADA.getValue()));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_REGIMEN_TRABAJADOR.getValue()));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_DEPARTAMENTO.getValue()));//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUCURSAL.getValue()));//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_PUESTO.getValue()));//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_RIESGO_PUESTO.getValue()));//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_FECHA_INGRESO_LABORAL.getValue()));//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ANTIGUEDAD.getValue()));//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SALARIO_DIARIO_BASE.getValue()));//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SALARIO_DIARIO_INTEGRADO.getValue()));//$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_TIPO_CONTRATO.getValue()));//$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_METODO_DE_PAGO.getValue()));//$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_REGISTRO_PATRONAL.getValue()));//$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_EMISOR_RFC.getValue()));//$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_DIAS_TRABAJADOS.getValue()));//$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_FALTAS.getValue()));//$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = (java.lang.String)(((java.lang.String)field_GRUPO.getValue()));//$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = (java.lang.String)(((java.math.BigDecimal)field_IMPORTE_EXENTO.getValue()));//$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = (java.lang.String)(((java.lang.String)field_DESCRIPCION.getValue()));//$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = (java.lang.String)(((java.math.BigDecimal)field_IMPORTE_GRAVADO.getValue()));//$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = (java.lang.String)(((java.lang.String)field_CLAVE.getValue()));//$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = (java.lang.String)("Página " + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()) + " de ");//$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = (java.lang.String)("" + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()));//$JR_EXPR_ID=61$
                break;
            }
            case 62 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_DESTINATARIO.getValue()));//$JR_EXPR_ID=62$
                break;
            }
            case 63 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)parameter_TOTAL.getValue()));//$JR_EXPR_ID=63$
                break;
            }
            case 64 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_IMP_CON_LETRA.getValue()));//$JR_EXPR_ID=64$
                break;
            }
            case 65 : 
            {
                value = (java.lang.String)("Página " + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()) + " de ");//$JR_EXPR_ID=65$
                break;
            }
            case 66 : 
            {
                value = (java.lang.String)("" + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()));//$JR_EXPR_ID=66$
                break;
            }
            case 67 : 
            {
                value = (java.lang.String)(((java.lang.Object)parameter_QR_CODE.getValue()));//$JR_EXPR_ID=67$
                break;
            }
            case 68 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_FECHA_TIMBRADO.getValue()));//$JR_EXPR_ID=68$
                break;
            }
            case 69 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_CERTIFICADO_SAT.getValue()));//$JR_EXPR_ID=69$
                break;
            }
            case 70 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_NUM_CERTIFICADO.getValue()));//$JR_EXPR_ID=70$
                break;
            }
            case 71 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_DESTINATARIO.getValue()));//$JR_EXPR_ID=71$
                break;
            }
            case 72 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_COMENTARIO_NOM.getValue()).concat("     RECIBI DE CONFORMIDAD:  Las prestaciones correspondientes al periodo que se indica arriba y que liquida totalmente hasta esta fecha mi salario normal, extra, 7° dia, salario de compensación y otras prestaciones, entiendo que las deducciones tanto legales como de caracter privado se han aplicado para cubrir los adeudos respectivos."));//$JR_EXPR_ID=72$
                break;
            }
            case 73 : 
            {
                value = (java.lang.String)(((java.lang.Integer)parameter_DIAS_HORAS_EXTRA.getValue()));//$JR_EXPR_ID=73$
                break;
            }
            case 74 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_TIPO_HORAS.getValue()));//$JR_EXPR_ID=74$
                break;
            }
            case 75 : 
            {
                value = (java.lang.String)(((java.math.BigDecimal)parameter_IMPORTE_HORAS_EXTRA.getValue()));//$JR_EXPR_ID=75$
                break;
            }
            case 76 : 
            {
                value = (java.lang.String)(((java.lang.Integer)parameter_HORAS_EXTRA.getValue()));//$JR_EXPR_ID=76$
                break;
            }
            case 77 : 
            {
                value = (java.lang.String)(((java.math.BigDecimal)parameter_DIAS_INCAPACIDAD.getValue()));//$JR_EXPR_ID=77$
                break;
            }
            case 78 : 
            {
                value = (java.lang.String)(((java.lang.Integer)parameter_TIPO_INCAPACIDAD.getValue()));//$JR_EXPR_ID=78$
                break;
            }
            case 79 : 
            {
                value = (java.lang.String)(((java.math.BigDecimal)parameter_IMPORTE_INCAPACIDAD.getValue()));//$JR_EXPR_ID=79$
                break;
            }
            case 80 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_CADENA_ORIGINAL_SAT.getValue()));//$JR_EXPR_ID=80$
                break;
            }
            case 81 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SELLO_DIGITAL.getValue()));//$JR_EXPR_ID=81$
                break;
            }
            case 82 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SELLO_DIGITAL_SAT.getValue()));//$JR_EXPR_ID=82$
                break;
            }
            case 83 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)parameter_SUB_EMPLEO_APLIC.getValue()));//$JR_EXPR_ID=83$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.String)("FALTA");//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.String)("N/A");//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.String)("N/A");//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.String)("N/A");//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_IMPORTE_EXENTO.getOldValue()));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_IMPORTE_GRAVADO.getOldValue()));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_CLAVE.getOldValue()).substring(0,1));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.lang.String)(((java.math.BigDecimal)variable_TOTAL_GRUPO_EXENTO.getOldValue()));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.lang.String)(" ".concat(((java.lang.String)field_CONCEPTO.getOldValue()).equals("P")?" PERCEPCIONES ":" DEDUCCIONES ").concat(" IMPORTE : "));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.lang.String)(new Double(((java.math.BigDecimal)variable_TOTAL_GRUPO_GRAVADO.getOldValue()).doubleValue()+((java.math.BigDecimal)variable_TOTAL_GRUPO_EXENTO.getOldValue()).doubleValue()));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.String)("TOTAL: ");//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.lang.String)(((java.math.BigDecimal)variable_TOTAL_GRUPO_GRAVADO.getOldValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_EMISOR_DIRECCION.getValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.String)(((java.lang.Object)parameter_EMPRESA_LOGO.getValue()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_FOLIO_FISCAL.getValue()));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_FECHA.getValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_NFISCAL.getValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_TIPO_NOMINA.getValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_FECHA_INICIAL.getValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_FECHA_FINAL.getValue()));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_PERIOCIDAD_PAGO.getValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_EMISOR_NOMBRE.getValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_BANCO.getValue()));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_CLABE.getValue()));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_NOMBRE.getValue()));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_NUMERO_IMSS.getValue()));//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_NUMERO_EMPLEADO.getValue()));//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_CURP.getValue()));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_RFC.getValue()));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_TIPO_JORNADA.getValue()));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_REGIMEN_TRABAJADOR.getValue()));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_DEPARTAMENTO.getValue()));//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUCURSAL.getValue()));//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_PUESTO.getValue()));//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_RIESGO_PUESTO.getValue()));//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_FECHA_INGRESO_LABORAL.getValue()));//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ANTIGUEDAD.getValue()));//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SALARIO_DIARIO_BASE.getValue()));//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SALARIO_DIARIO_INTEGRADO.getValue()));//$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_TIPO_CONTRATO.getValue()));//$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_METODO_DE_PAGO.getValue()));//$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_REGISTRO_PATRONAL.getValue()));//$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_EMISOR_RFC.getValue()));//$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_DIAS_TRABAJADOS.getValue()));//$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_FALTAS.getValue()));//$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = (java.lang.String)(((java.lang.String)field_GRUPO.getOldValue()));//$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = (java.lang.String)(((java.math.BigDecimal)field_IMPORTE_EXENTO.getOldValue()));//$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = (java.lang.String)(((java.lang.String)field_DESCRIPCION.getOldValue()));//$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = (java.lang.String)(((java.math.BigDecimal)field_IMPORTE_GRAVADO.getOldValue()));//$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = (java.lang.String)(((java.lang.String)field_CLAVE.getOldValue()));//$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = (java.lang.String)("Página " + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()) + " de ");//$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = (java.lang.String)("" + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));//$JR_EXPR_ID=61$
                break;
            }
            case 62 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_DESTINATARIO.getValue()));//$JR_EXPR_ID=62$
                break;
            }
            case 63 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)parameter_TOTAL.getValue()));//$JR_EXPR_ID=63$
                break;
            }
            case 64 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_IMP_CON_LETRA.getValue()));//$JR_EXPR_ID=64$
                break;
            }
            case 65 : 
            {
                value = (java.lang.String)("Página " + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()) + " de ");//$JR_EXPR_ID=65$
                break;
            }
            case 66 : 
            {
                value = (java.lang.String)("" + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));//$JR_EXPR_ID=66$
                break;
            }
            case 67 : 
            {
                value = (java.lang.String)(((java.lang.Object)parameter_QR_CODE.getValue()));//$JR_EXPR_ID=67$
                break;
            }
            case 68 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_FECHA_TIMBRADO.getValue()));//$JR_EXPR_ID=68$
                break;
            }
            case 69 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_CERTIFICADO_SAT.getValue()));//$JR_EXPR_ID=69$
                break;
            }
            case 70 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_NUM_CERTIFICADO.getValue()));//$JR_EXPR_ID=70$
                break;
            }
            case 71 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_DESTINATARIO.getValue()));//$JR_EXPR_ID=71$
                break;
            }
            case 72 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_COMENTARIO_NOM.getValue()).concat("     RECIBI DE CONFORMIDAD:  Las prestaciones correspondientes al periodo que se indica arriba y que liquida totalmente hasta esta fecha mi salario normal, extra, 7° dia, salario de compensación y otras prestaciones, entiendo que las deducciones tanto legales como de caracter privado se han aplicado para cubrir los adeudos respectivos."));//$JR_EXPR_ID=72$
                break;
            }
            case 73 : 
            {
                value = (java.lang.String)(((java.lang.Integer)parameter_DIAS_HORAS_EXTRA.getValue()));//$JR_EXPR_ID=73$
                break;
            }
            case 74 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_TIPO_HORAS.getValue()));//$JR_EXPR_ID=74$
                break;
            }
            case 75 : 
            {
                value = (java.lang.String)(((java.math.BigDecimal)parameter_IMPORTE_HORAS_EXTRA.getValue()));//$JR_EXPR_ID=75$
                break;
            }
            case 76 : 
            {
                value = (java.lang.String)(((java.lang.Integer)parameter_HORAS_EXTRA.getValue()));//$JR_EXPR_ID=76$
                break;
            }
            case 77 : 
            {
                value = (java.lang.String)(((java.math.BigDecimal)parameter_DIAS_INCAPACIDAD.getValue()));//$JR_EXPR_ID=77$
                break;
            }
            case 78 : 
            {
                value = (java.lang.String)(((java.lang.Integer)parameter_TIPO_INCAPACIDAD.getValue()));//$JR_EXPR_ID=78$
                break;
            }
            case 79 : 
            {
                value = (java.lang.String)(((java.math.BigDecimal)parameter_IMPORTE_INCAPACIDAD.getValue()));//$JR_EXPR_ID=79$
                break;
            }
            case 80 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_CADENA_ORIGINAL_SAT.getValue()));//$JR_EXPR_ID=80$
                break;
            }
            case 81 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SELLO_DIGITAL.getValue()));//$JR_EXPR_ID=81$
                break;
            }
            case 82 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SELLO_DIGITAL_SAT.getValue()));//$JR_EXPR_ID=82$
                break;
            }
            case 83 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)parameter_SUB_EMPLEO_APLIC.getValue()));//$JR_EXPR_ID=83$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.String)("FALTA");//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.String)("N/A");//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.String)("N/A");//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.String)("N/A");//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_IMPORTE_EXENTO.getValue()));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_IMPORTE_GRAVADO.getValue()));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_CLAVE.getValue()).substring(0,1));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.lang.String)(((java.math.BigDecimal)variable_TOTAL_GRUPO_EXENTO.getEstimatedValue()));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.lang.String)(" ".concat(((java.lang.String)field_CONCEPTO.getValue()).equals("P")?" PERCEPCIONES ":" DEDUCCIONES ").concat(" IMPORTE : "));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.lang.String)(new Double(((java.math.BigDecimal)variable_TOTAL_GRUPO_GRAVADO.getEstimatedValue()).doubleValue()+((java.math.BigDecimal)variable_TOTAL_GRUPO_EXENTO.getEstimatedValue()).doubleValue()));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.String)("TOTAL: ");//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.lang.String)(((java.math.BigDecimal)variable_TOTAL_GRUPO_GRAVADO.getEstimatedValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_EMISOR_DIRECCION.getValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.String)(((java.lang.Object)parameter_EMPRESA_LOGO.getValue()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_FOLIO_FISCAL.getValue()));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_FECHA.getValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_NFISCAL.getValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_TIPO_NOMINA.getValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_FECHA_INICIAL.getValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_FECHA_FINAL.getValue()));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_PERIOCIDAD_PAGO.getValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_EMISOR_NOMBRE.getValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_BANCO.getValue()));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_CLABE.getValue()));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_NOMBRE.getValue()));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_NUMERO_IMSS.getValue()));//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_NUMERO_EMPLEADO.getValue()));//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_CURP.getValue()));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_RFC.getValue()));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_TIPO_JORNADA.getValue()));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_REGIMEN_TRABAJADOR.getValue()));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_DEPARTAMENTO.getValue()));//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUCURSAL.getValue()));//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_PUESTO.getValue()));//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_RIESGO_PUESTO.getValue()));//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_FECHA_INGRESO_LABORAL.getValue()));//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ANTIGUEDAD.getValue()));//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SALARIO_DIARIO_BASE.getValue()));//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SALARIO_DIARIO_INTEGRADO.getValue()));//$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_TIPO_CONTRATO.getValue()));//$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_METODO_DE_PAGO.getValue()));//$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_REGISTRO_PATRONAL.getValue()));//$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_EMISOR_RFC.getValue()));//$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_DIAS_TRABAJADOS.getValue()));//$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_FALTAS.getValue()));//$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = (java.lang.String)(((java.lang.String)field_GRUPO.getValue()));//$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = (java.lang.String)(((java.math.BigDecimal)field_IMPORTE_EXENTO.getValue()));//$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = (java.lang.String)(((java.lang.String)field_DESCRIPCION.getValue()));//$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = (java.lang.String)(((java.math.BigDecimal)field_IMPORTE_GRAVADO.getValue()));//$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = (java.lang.String)(((java.lang.String)field_CLAVE.getValue()));//$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = (java.lang.String)("Página " + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()) + " de ");//$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = (java.lang.String)("" + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));//$JR_EXPR_ID=61$
                break;
            }
            case 62 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_DESTINATARIO.getValue()));//$JR_EXPR_ID=62$
                break;
            }
            case 63 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)parameter_TOTAL.getValue()));//$JR_EXPR_ID=63$
                break;
            }
            case 64 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_IMP_CON_LETRA.getValue()));//$JR_EXPR_ID=64$
                break;
            }
            case 65 : 
            {
                value = (java.lang.String)("Página " + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()) + " de ");//$JR_EXPR_ID=65$
                break;
            }
            case 66 : 
            {
                value = (java.lang.String)("" + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));//$JR_EXPR_ID=66$
                break;
            }
            case 67 : 
            {
                value = (java.lang.String)(((java.lang.Object)parameter_QR_CODE.getValue()));//$JR_EXPR_ID=67$
                break;
            }
            case 68 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_FECHA_TIMBRADO.getValue()));//$JR_EXPR_ID=68$
                break;
            }
            case 69 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_CERTIFICADO_SAT.getValue()));//$JR_EXPR_ID=69$
                break;
            }
            case 70 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_NUM_CERTIFICADO.getValue()));//$JR_EXPR_ID=70$
                break;
            }
            case 71 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_DESTINATARIO.getValue()));//$JR_EXPR_ID=71$
                break;
            }
            case 72 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_COMENTARIO_NOM.getValue()).concat("     RECIBI DE CONFORMIDAD:  Las prestaciones correspondientes al periodo que se indica arriba y que liquida totalmente hasta esta fecha mi salario normal, extra, 7° dia, salario de compensación y otras prestaciones, entiendo que las deducciones tanto legales como de caracter privado se han aplicado para cubrir los adeudos respectivos."));//$JR_EXPR_ID=72$
                break;
            }
            case 73 : 
            {
                value = (java.lang.String)(((java.lang.Integer)parameter_DIAS_HORAS_EXTRA.getValue()));//$JR_EXPR_ID=73$
                break;
            }
            case 74 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_TIPO_HORAS.getValue()));//$JR_EXPR_ID=74$
                break;
            }
            case 75 : 
            {
                value = (java.lang.String)(((java.math.BigDecimal)parameter_IMPORTE_HORAS_EXTRA.getValue()));//$JR_EXPR_ID=75$
                break;
            }
            case 76 : 
            {
                value = (java.lang.String)(((java.lang.Integer)parameter_HORAS_EXTRA.getValue()));//$JR_EXPR_ID=76$
                break;
            }
            case 77 : 
            {
                value = (java.lang.String)(((java.math.BigDecimal)parameter_DIAS_INCAPACIDAD.getValue()));//$JR_EXPR_ID=77$
                break;
            }
            case 78 : 
            {
                value = (java.lang.String)(((java.lang.Integer)parameter_TIPO_INCAPACIDAD.getValue()));//$JR_EXPR_ID=78$
                break;
            }
            case 79 : 
            {
                value = (java.lang.String)(((java.math.BigDecimal)parameter_IMPORTE_INCAPACIDAD.getValue()));//$JR_EXPR_ID=79$
                break;
            }
            case 80 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_CADENA_ORIGINAL_SAT.getValue()));//$JR_EXPR_ID=80$
                break;
            }
            case 81 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SELLO_DIGITAL.getValue()));//$JR_EXPR_ID=81$
                break;
            }
            case 82 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SELLO_DIGITAL_SAT.getValue()));//$JR_EXPR_ID=82$
                break;
            }
            case 83 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)parameter_SUB_EMPLEO_APLIC.getValue()));//$JR_EXPR_ID=83$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
