//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.29 at 07:51:27 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(
        namespace = "http://www.sat.gob.mx/esquemas/retencionpago/1",
        xmlns= {
                @XmlNs(prefix = "retenciones",namespaceURI="http://www.sat.gob.mx/esquemas/retencionpago/1")
        },
        elementFormDefault= XmlNsForm.QUALIFIED)
package com.luxsoft.cfdi.retenciones;
import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlNsForm;
