//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.29 at 07:51:27 PM CDT 
//


package com.luxsoft.cfdi.retenciones;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.Date;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Emisor">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="RFCEmisor" use="required" type="{http://www.sat.gob.mx/esquemas/retencionpago/1}t_RFC" />
 *                 &lt;attribute name="NomDenRazSocE">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;minLength value="1"/>
 *                       &lt;maxLength value="300"/>
 *                       &lt;whiteSpace value="collapse"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="CURPE" type="{http://www.sat.gob.mx/esquemas/retencionpago/1}t_CURP" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Receptor">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="Nacional">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="RFCRecep" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.sat.gob.mx/esquemas/retencionpago/1}t_RFC">
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="NomDenRazSocR">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;minLength value="1"/>
 *                                 &lt;maxLength value="300"/>
 *                                 &lt;whiteSpace value="collapse"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="CURPR" type="{http://www.sat.gob.mx/esquemas/retencionpago/1}t_CURP" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Extranjero">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="NumRegIdTrib">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;minLength value="1"/>
 *                                 &lt;maxLength value="20"/>
 *                                 &lt;whiteSpace value="collapse"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="NomDenRazSocR" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;minLength value="1"/>
 *                                 &lt;maxLength value="300"/>
 *                                 &lt;whiteSpace value="collapse"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *                 &lt;attribute name="Nacionalidad" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;whiteSpace value="collapse"/>
 *                       &lt;enumeration value="Nacional"/>
 *                       &lt;enumeration value="Extranjero"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Periodo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="MesIni" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                       &lt;minInclusive value="1"/>
 *                       &lt;maxInclusive value="12"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="MesFin" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                       &lt;minInclusive value="1"/>
 *                       &lt;maxInclusive value="12"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="Ejerc" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                       &lt;minInclusive value="2004"/>
 *                       &lt;maxInclusive value="2024"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Totales">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ImpRetenidos" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="BaseRet" type="{http://www.sat.gob.mx/esquemas/retencionpago/1}t_Importe" />
 *                           &lt;attribute name="Impuesto">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.sat.gob.mx/esquemas/retencionpago/1/catalogos}c_TipoImpuesto">
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="montoRet" use="required" type="{http://www.sat.gob.mx/esquemas/retencionpago/1}t_Importe" />
 *                           &lt;attribute name="TipoPagoRet" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;whiteSpace value="collapse"/>
 *                                 &lt;enumeration value="Pago definitivo"/>
 *                                 &lt;enumeration value="Pago provisional"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="montoTotOperacion" use="required" type="{http://www.sat.gob.mx/esquemas/retencionpago/1}t_Importe" />
 *                 &lt;attribute name="montoTotGrav" use="required" type="{http://www.sat.gob.mx/esquemas/retencionpago/1}t_Importe" />
 *                 &lt;attribute name="montoTotExent" use="required" type="{http://www.sat.gob.mx/esquemas/retencionpago/1}t_Importe" />
 *                 &lt;attribute name="montoTotRet" use="required" type="{http://www.sat.gob.mx/esquemas/retencionpago/1}t_Importe" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Complemento" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;any maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Addenda" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;any maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Version" use="required" fixed="1.0">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;whiteSpace value="collapse"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="FolioInt">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;maxLength value="20"/>
 *             &lt;whiteSpace value="collapse"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Sello" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;whiteSpace value="collapse"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="NumCert" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;length value="20"/>
 *             &lt;whiteSpace value="collapse"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Cert" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;whiteSpace value="collapse"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="FechaExp" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}dateTime">
 *             &lt;whiteSpace value="collapse"/>
 *             &lt;minInclusive value="2014-01-01T00:00:00-06:00"/>
 *             &lt;pattern value="-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CveRetenc" use="required" type="{http://www.sat.gob.mx/esquemas/retencionpago/1/catalogos}c_Retenciones" />
 *       &lt;attribute name="DescRetenc">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;maxLength value="100"/>
 *             &lt;whiteSpace value="collapse"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "emisor",
    "receptor",
    "periodo",
    "totales",
    "complemento",
    "addenda"
})
@XmlRootElement(name = "Retenciones")
public class Retenciones {

    @XmlElement(name = "Emisor", required = true)
    protected Retenciones.Emisor emisor;
    @XmlElement(name = "Receptor", required = true)
    protected Retenciones.Receptor receptor;
    @XmlElement(name = "Periodo", required = true)
    protected Retenciones.Periodo periodo;
    @XmlElement(name = "Totales", required = true)
    protected Retenciones.Totales totales;
    @XmlElement(name = "Complemento")
    protected Retenciones.Complemento complemento;
    @XmlElement(name = "Addenda")
    protected Retenciones.Addenda addenda;
    @XmlAttribute(name = "Version", required = true)
    protected String version;
    @XmlAttribute(name = "FolioInt")
    protected String folioInt;
    @XmlAttribute(name = "Sello", required = true)
    protected String sello;
    @XmlAttribute(name = "NumCert", required = true)
    protected String numCert;
    @XmlAttribute(name = "Cert", required = true)
    protected String cert;
    @XmlAttribute(name = "FechaExp", required = true)
    protected Date fechaExp;
    @XmlAttribute(name = "CveRetenc", required = true)
    protected String cveRetenc;
    @XmlAttribute(name = "DescRetenc")
    protected String descRetenc;

    /**
     * Gets the value of the emisor property.
     * 
     * @return
     *     possible object is
     *     {@link Retenciones.Emisor }
     *     
     */
    public Retenciones.Emisor getEmisor() {
        return emisor;
    }

    /**
     * Sets the value of the emisor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Retenciones.Emisor }
     *     
     */
    public void setEmisor(Retenciones.Emisor value) {
        this.emisor = value;
    }

    /**
     * Gets the value of the receptor property.
     * 
     * @return
     *     possible object is
     *     {@link Retenciones.Receptor }
     *     
     */
    public Retenciones.Receptor getReceptor() {
        return receptor;
    }

    /**
     * Sets the value of the receptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Retenciones.Receptor }
     *     
     */
    public void setReceptor(Retenciones.Receptor value) {
        this.receptor = value;
    }

    /**
     * Gets the value of the periodo property.
     * 
     * @return
     *     possible object is
     *     {@link Retenciones.Periodo }
     *     
     */
    public Retenciones.Periodo getPeriodo() {
        return periodo;
    }

    /**
     * Sets the value of the periodo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Retenciones.Periodo }
     *     
     */
    public void setPeriodo(Retenciones.Periodo value) {
        this.periodo = value;
    }

    /**
     * Gets the value of the totales property.
     * 
     * @return
     *     possible object is
     *     {@link Retenciones.Totales }
     *     
     */
    public Retenciones.Totales getTotales() {
        return totales;
    }

    /**
     * Sets the value of the totales property.
     * 
     * @param value
     *     allowed object is
     *     {@link Retenciones.Totales }
     *     
     */
    public void setTotales(Retenciones.Totales value) {
        this.totales = value;
    }

    /**
     * Gets the value of the complemento property.
     * 
     * @return
     *     possible object is
     *     {@link Retenciones.Complemento }
     *     
     */
    public Retenciones.Complemento getComplemento() {
        return complemento;
    }

    /**
     * Sets the value of the complemento property.
     * 
     * @param value
     *     allowed object is
     *     {@link Retenciones.Complemento }
     *     
     */
    public void setComplemento(Retenciones.Complemento value) {
        this.complemento = value;
    }

    /**
     * Gets the value of the addenda property.
     * 
     * @return
     *     possible object is
     *     {@link Retenciones.Addenda }
     *     
     */
    public Retenciones.Addenda getAddenda() {
        return addenda;
    }

    /**
     * Sets the value of the addenda property.
     * 
     * @param value
     *     allowed object is
     *     {@link Retenciones.Addenda }
     *     
     */
    public void setAddenda(Retenciones.Addenda value) {
        this.addenda = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the folioInt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFolioInt() {
        return folioInt;
    }

    /**
     * Sets the value of the folioInt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFolioInt(String value) {
        this.folioInt = value;
    }

    /**
     * Gets the value of the sello property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSello() {
        return sello;
    }

    /**
     * Sets the value of the sello property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSello(String value) {
        this.sello = value;
    }

    /**
     * Gets the value of the numCert property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumCert() {
        return numCert;
    }

    /**
     * Sets the value of the numCert property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumCert(String value) {
        this.numCert = value;
    }

    /**
     * Gets the value of the cert property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCert() {
        return cert;
    }

    /**
     * Sets the value of the cert property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCert(String value) {
        this.cert = value;
    }

    
    public Date getFechaExp() {
        return fechaExp;
    }

    
    public void setFechaExp(Date value) {
        this.fechaExp = value;
    }

    /**
     * Gets the value of the cveRetenc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCveRetenc() {
        return cveRetenc;
    }

    /**
     * Sets the value of the cveRetenc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCveRetenc(String value) {
        this.cveRetenc = value;
    }

    /**
     * Gets the value of the descRetenc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescRetenc() {
        return descRetenc;
    }

    /**
     * Sets the value of the descRetenc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescRetenc(String value) {
        this.descRetenc = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;any maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "any"
    })
    public static class Addenda {

        @XmlAnyElement(lax = true)
        protected List<Object> any;

        /**
         * Gets the value of the any property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the any property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAny().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Object }
         * 
         * 
         */
        public List<Object> getAny() {
            if (any == null) {
                any = new ArrayList<Object>();
            }
            return this.any;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;any maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "any"
    })
    public static class Complemento {

        @XmlAnyElement(lax = true)
        protected List<Object> any;

        /**
         * Gets the value of the any property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the any property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAny().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Object }
         * 
         * 
         */
        public List<Object> getAny() {
            if (any == null) {
                any = new ArrayList<Object>();
            }
            return this.any;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="RFCEmisor" use="required" type="{http://www.sat.gob.mx/esquemas/retencionpago/1}t_RFC" />
     *       &lt;attribute name="NomDenRazSocE">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;minLength value="1"/>
     *             &lt;maxLength value="300"/>
     *             &lt;whiteSpace value="collapse"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="CURPE" type="{http://www.sat.gob.mx/esquemas/retencionpago/1}t_CURP" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Emisor {

        @XmlAttribute(name = "RFCEmisor", required = true)
        protected String rfcEmisor;
        @XmlAttribute(name = "NomDenRazSocE")
        protected String nomDenRazSocE;
        @XmlAttribute(name = "CURPE")
        protected String curpe;

        /**
         * Gets the value of the rfcEmisor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRFCEmisor() {
            return rfcEmisor;
        }

        /**
         * Sets the value of the rfcEmisor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRFCEmisor(String value) {
            this.rfcEmisor = value;
        }

        /**
         * Gets the value of the nomDenRazSocE property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNomDenRazSocE() {
            return nomDenRazSocE;
        }

        /**
         * Sets the value of the nomDenRazSocE property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNomDenRazSocE(String value) {
            this.nomDenRazSocE = value;
        }

        /**
         * Gets the value of the curpe property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCURPE() {
            return curpe;
        }

        /**
         * Sets the value of the curpe property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCURPE(String value) {
            this.curpe = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="MesIni" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *             &lt;minInclusive value="1"/>
     *             &lt;maxInclusive value="12"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="MesFin" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *             &lt;minInclusive value="1"/>
     *             &lt;maxInclusive value="12"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="Ejerc" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *             &lt;minInclusive value="2004"/>
     *             &lt;maxInclusive value="2024"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Periodo {

        @XmlAttribute(name = "MesIni", required = true)
        protected int mesIni;
        @XmlAttribute(name = "MesFin", required = true)
        protected int mesFin;
        @XmlAttribute(name = "Ejerc", required = true)
        protected int ejerc;

        /**
         * Gets the value of the mesIni property.
         * 
         */
        public int getMesIni() {
            return mesIni;
        }

        /**
         * Sets the value of the mesIni property.
         * 
         */
        public void setMesIni(int value) {
            this.mesIni = value;
        }

        /**
         * Gets the value of the mesFin property.
         * 
         */
        public int getMesFin() {
            return mesFin;
        }

        /**
         * Sets the value of the mesFin property.
         * 
         */
        public void setMesFin(int value) {
            this.mesFin = value;
        }

        /**
         * Gets the value of the ejerc property.
         * 
         */
        public int getEjerc() {
            return ejerc;
        }

        /**
         * Sets the value of the ejerc property.
         * 
         */
        public void setEjerc(int value) {
            this.ejerc = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="Nacional">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="RFCRecep" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.sat.gob.mx/esquemas/retencionpago/1}t_RFC">
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="NomDenRazSocR">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;minLength value="1"/>
     *                       &lt;maxLength value="300"/>
     *                       &lt;whiteSpace value="collapse"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="CURPR" type="{http://www.sat.gob.mx/esquemas/retencionpago/1}t_CURP" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Extranjero">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="NumRegIdTrib">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;minLength value="1"/>
     *                       &lt;maxLength value="20"/>
     *                       &lt;whiteSpace value="collapse"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="NomDenRazSocR" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;minLength value="1"/>
     *                       &lt;maxLength value="300"/>
     *                       &lt;whiteSpace value="collapse"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *       &lt;attribute name="Nacionalidad" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;whiteSpace value="collapse"/>
     *             &lt;enumeration value="Nacional"/>
     *             &lt;enumeration value="Extranjero"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nacional",
        "extranjero"
    })
    public static class Receptor {

        @XmlElement(name = "Nacional")
        protected Retenciones.Receptor.Nacional nacional;

        @XmlElement(name = "Extranjero")
        protected Retenciones.Receptor.Extranjero extranjero;
        
        @XmlAttribute(name = "Nacionalidad", required = true)
        protected String nacionalidad;

        /**
         * Gets the value of the nacional property.
         * 
         * @return
         *     possible object is
         *     {@link Retenciones.Receptor.Nacional }
         *     
         */
        public Retenciones.Receptor.Nacional getNacional() {
            return nacional;
        }

        /**
         * Sets the value of the nacional property.
         * 
         * @param value
         *     allowed object is
         *     {@link Retenciones.Receptor.Nacional }
         *     
         */
        public void setNacional(Retenciones.Receptor.Nacional value) {
            this.nacional = value;
        }

        /**
         * Gets the value of the extranjero property.
         * 
         * @return
         *     possible object is
         *     {@link Retenciones.Receptor.Extranjero }
         *     
         */
        public Retenciones.Receptor.Extranjero getExtranjero() {
            return extranjero;
        }

        /**
         * Sets the value of the extranjero property.
         * 
         * @param value
         *     allowed object is
         *     {@link Retenciones.Receptor.Extranjero }
         *     
         */
        public void setExtranjero(Retenciones.Receptor.Extranjero value) {
            this.extranjero = value;
        }

        /**
         * Gets the value of the nacionalidad property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNacionalidad() {
            return nacionalidad;
        }

        /**
         * Sets the value of the nacionalidad property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNacionalidad(String value) {
            this.nacionalidad = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="NumRegIdTrib">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;minLength value="1"/>
         *             &lt;maxLength value="20"/>
         *             &lt;whiteSpace value="collapse"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="NomDenRazSocR" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;minLength value="1"/>
         *             &lt;maxLength value="300"/>
         *             &lt;whiteSpace value="collapse"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Extranjero {

            @XmlAttribute(name = "NumRegIdTrib")
            protected String numRegIdTrib;
            @XmlAttribute(name = "NomDenRazSocR", required = true)
            protected String nomDenRazSocR;

            /**
             * Gets the value of the numRegIdTrib property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNumRegIdTrib() {
                return numRegIdTrib;
            }

            /**
             * Sets the value of the numRegIdTrib property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNumRegIdTrib(String value) {
                this.numRegIdTrib = value;
            }

            /**
             * Gets the value of the nomDenRazSocR property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNomDenRazSocR() {
                return nomDenRazSocR;
            }

            /**
             * Sets the value of the nomDenRazSocR property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNomDenRazSocR(String value) {
                this.nomDenRazSocR = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="RFCRecep" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.sat.gob.mx/esquemas/retencionpago/1}t_RFC">
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="NomDenRazSocR">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;minLength value="1"/>
         *             &lt;maxLength value="300"/>
         *             &lt;whiteSpace value="collapse"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="CURPR" type="{http://www.sat.gob.mx/esquemas/retencionpago/1}t_CURP" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Nacional {

            @XmlAttribute(name = "RFCRecep", required = true)
            protected String rfcRecep;
            @XmlAttribute(name = "NomDenRazSocR")
            protected String nomDenRazSocR;
            @XmlAttribute(name = "CURPR")
            protected String curpr;

            /**
             * Gets the value of the rfcRecep property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRFCRecep() {
                return rfcRecep;
            }

            /**
             * Sets the value of the rfcRecep property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRFCRecep(String value) {
                this.rfcRecep = value;
            }

            /**
             * Gets the value of the nomDenRazSocR property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNomDenRazSocR() {
                return nomDenRazSocR;
            }

            /**
             * Sets the value of the nomDenRazSocR property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNomDenRazSocR(String value) {
                this.nomDenRazSocR = value;
            }

            /**
             * Gets the value of the curpr property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCURPR() {
                return curpr;
            }

            /**
             * Sets the value of the curpr property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCURPR(String value) {
                this.curpr = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ImpRetenidos" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="BaseRet" type="{http://www.sat.gob.mx/esquemas/retencionpago/1}t_Importe" />
     *                 &lt;attribute name="Impuesto">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.sat.gob.mx/esquemas/retencionpago/1/catalogos}c_TipoImpuesto">
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="montoRet" use="required" type="{http://www.sat.gob.mx/esquemas/retencionpago/1}t_Importe" />
     *                 &lt;attribute name="TipoPagoRet" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;whiteSpace value="collapse"/>
     *                       &lt;enumeration value="Pago definitivo"/>
     *                       &lt;enumeration value="Pago provisional"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="montoTotOperacion" use="required" type="{http://www.sat.gob.mx/esquemas/retencionpago/1}t_Importe" />
     *       &lt;attribute name="montoTotGrav" use="required" type="{http://www.sat.gob.mx/esquemas/retencionpago/1}t_Importe" />
     *       &lt;attribute name="montoTotExent" use="required" type="{http://www.sat.gob.mx/esquemas/retencionpago/1}t_Importe" />
     *       &lt;attribute name="montoTotRet" use="required" type="{http://www.sat.gob.mx/esquemas/retencionpago/1}t_Importe" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "impRetenidos"
    })
    public static class Totales {

        @XmlElement(name = "ImpRetenidos")
        protected List<Retenciones.Totales.ImpRetenidos> impRetenidos;
        @XmlAttribute(name = "montoTotOperacion", required = true)
        protected BigDecimal montoTotOperacion;
        @XmlAttribute(name = "montoTotGrav", required = true)
        protected BigDecimal montoTotGrav;
        @XmlAttribute(name = "montoTotExent", required = true)
        protected BigDecimal montoTotExent;
        @XmlAttribute(name = "montoTotRet", required = true)
        protected BigDecimal montoTotRet;

        /**
         * Gets the value of the impRetenidos property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the impRetenidos property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getImpRetenidos().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Retenciones.Totales.ImpRetenidos }
         * 
         * 
         */
        public List<Retenciones.Totales.ImpRetenidos> getImpRetenidos() {
            if (impRetenidos == null) {
                impRetenidos = new ArrayList<Retenciones.Totales.ImpRetenidos>();
            }
            return this.impRetenidos;
        }

        /**
         * Gets the value of the montoTotOperacion property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getMontoTotOperacion() {
            return montoTotOperacion;
        }

        /**
         * Sets the value of the montoTotOperacion property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setMontoTotOperacion(BigDecimal value) {
            this.montoTotOperacion = value;
        }

        /**
         * Gets the value of the montoTotGrav property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getMontoTotGrav() {
            return montoTotGrav;
        }

        /**
         * Sets the value of the montoTotGrav property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setMontoTotGrav(BigDecimal value) {
            this.montoTotGrav = value;
        }

        /**
         * Gets the value of the montoTotExent property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getMontoTotExent() {
            return montoTotExent;
        }

        /**
         * Sets the value of the montoTotExent property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setMontoTotExent(BigDecimal value) {
            this.montoTotExent = value;
        }

        /**
         * Gets the value of the montoTotRet property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getMontoTotRet() {
            return montoTotRet;
        }

        /**
         * Sets the value of the montoTotRet property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setMontoTotRet(BigDecimal value) {
            this.montoTotRet = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="BaseRet" type="{http://www.sat.gob.mx/esquemas/retencionpago/1}t_Importe" />
         *       &lt;attribute name="Impuesto">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.sat.gob.mx/esquemas/retencionpago/1/catalogos}c_TipoImpuesto">
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="montoRet" use="required" type="{http://www.sat.gob.mx/esquemas/retencionpago/1}t_Importe" />
         *       &lt;attribute name="TipoPagoRet" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;whiteSpace value="collapse"/>
         *             &lt;enumeration value="Pago definitivo"/>
         *             &lt;enumeration value="Pago provisional"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class ImpRetenidos {

            @XmlAttribute(name = "BaseRet")
            protected BigDecimal baseRet;
            @XmlAttribute(name = "Impuesto")
            protected String impuesto;
            @XmlAttribute(name = "montoRet", required = true)
            protected BigDecimal montoRet;
            @XmlAttribute(name = "TipoPagoRet", required = true)
            protected String tipoPagoRet;

            /**
             * Gets the value of the baseRet property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getBaseRet() {
                return baseRet;
            }

            /**
             * Sets the value of the baseRet property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setBaseRet(BigDecimal value) {
                this.baseRet = value;
            }

            /**
             * Gets the value of the impuesto property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getImpuesto() {
                return impuesto;
            }

            /**
             * Sets the value of the impuesto property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setImpuesto(String value) {
                this.impuesto = value;
            }

            /**
             * Gets the value of the montoRet property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getMontoRet() {
                return montoRet;
            }

            /**
             * Sets the value of the montoRet property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setMontoRet(BigDecimal value) {
                this.montoRet = value;
            }

            /**
             * Gets the value of the tipoPagoRet property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTipoPagoRet() {
                return tipoPagoRet;
            }

            /**
             * Sets the value of the tipoPagoRet property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTipoPagoRet(String value) {
                this.tipoPagoRet = value;
            }

        }

    }

}
